# Generated by Django 5.2.7 on 2025-10-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='image_url',
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='featured_images/'),
        ),
    ]
