# Generated by Django 5.2.7 on 2025-10-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_featuredpost_image_url_featuredpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('anime_name', models.CharField(blank=True, help_text='Anime or series name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Short description or story behind the image')),
                ('file', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
