# Generated by Django 5.2.7 on 2025-10-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='anime_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
