# Generated by Django 5.2.7 on 2025-10-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_gallery_options_alter_gallery_anime_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='featured_videos/'),
        ),
    ]
