# Generated by Django 5.2.7 on 2025-10-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_featuredpost_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuredpost',
            old_name='video',
            new_name='video_file',
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
