# Generated by Django 5.2.7 on 2025-10-13 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_video_featuredpost_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='video_file',
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='uploaded_video',
            field=models.FileField(blank=True, help_text='Upload a local video file (optional)', null=True, upload_to='featured_videos/'),
        ),
        migrations.AlterField(
            model_name='featuredpost',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube link (optional)'),
        ),
    ]
